from __future__ import annotations

import json
from pathlib import Path

from typer.testing import CliRunner

from fairypcbot.cli import app

runner = CliRunner()


def test_elaborate_reference_clean(reference_example: Path):
    result = runner.invoke(app, ["elaborate", "-p", str(reference_example), "--json", "--no-audit"])
    assert result.exit_code == 0
    data = json.loads(result.stdout)
    assert data["ok"] is True
    assert data["errors"] == []
    assert data["warnings"] == []
    # cleans artifacts generated by the actual command (netlist.json/rules.json in build/)
    for f in ("netlist.json", "rules.json"):
        p = reference_example / "build" / f
        if p.exists():
            p.unlink()


def test_elaborate_intentional_error(repo_root: Path):
    fixture = repo_root / "tests" / "elaborate" / "fixtures" / "bad_circuit"
    result = runner.invoke(app, ["elaborate", "-p", str(fixture), "--json", "--no-audit"])
    assert result.exit_code == 1
    data = json.loads(result.stdout)
    assert data["ok"] is False
    codes = {e["code"] for e in data["errors"]}
    assert "E_POWER_TREE_UNREACHABLE" in codes
    warning_codes = {w["code"] for w in data["warnings"]}
    assert "W_CURRENT_OVER_TRACE_CAPACITY" in warning_codes

    for f in ("netlist.json", "rules.json"):
        p = fixture / "build" / f
        if p.exists():
            p.unlink()
    build_dir = fixture / "build"
    if build_dir.exists() and not any(build_dir.iterdir()):
        build_dir.rmdir()
