"""Pydantic schema for object descriptors (`library/parts/*.yaml`, spec section 3.3).

`class_` and `pinout` are optional to accommodate the *stub* generated by `catalog fetch`
(section 7): the catalog never invents data, so fields that were not obtained are left
absent/empty with `missing` provenance, and it is up to the LLM to complete them from the
datasheet.
"""

from __future__ import annotations

import re
from typing import Any, Literal

from pydantic import Field, field_validator

from fairypcbot.schemas.base import FairyBaseModel
from fairypcbot.schemas.footprint import Footprint
from fairypcbot.schemas.provenance import Provenance
from fairypcbot.schemas.symbol import Symbol

_LCSC_ID_RE = re.compile(r"^lcsc:C\d+$")


class PackageSpec(FairyBaseModel):
    name: str
    source: str
    # Reference to a component_package in the library ("family" or "family:variant") — see
    # schemas/component_package.py. When present, takes precedence over an embedded
    # `footprint` on this part (fallback for old stubs without a library package).
    ref: str | None = None


class Model3D(FairyBaseModel):
    """Link to the official EasyEDA 3D model (platform-internal uuid) — never a binary
    downloaded by this framework (see the documentation: a raw HTTP download of the model failed,
    403/404 without an app session; the model is only actually resolved by the authenticated
    Pro app, via `LIB_3DModel` or when placing the official device). We only keep the
    reference so the `.eprj2` emitter can attach the `3D Model`/`3D Model Title` attrs to the
    device — Pro resolves the binary itself on open."""

    uuid: str
    name: str | None = None


class ComponentPart(FairyBaseModel):
    fairypcbot: str = "0.1"
    kind: Literal["component_part"]
    id: str
    class_: str | None = Field(default=None, alias="class")
    mpn: str
    manufacturer: str
    package: PackageSpec
    pinout: dict[str, str | int | list[str | int]] = {}
    params: dict[str, Any] = {}
    datasheet_url: str | None = None
    datasheet_ref: str | None = None  # id of a datasheet_extract in library/datasheets/
    footprint: Footprint | None = None
    symbol: Symbol | None = None
    model_3d: Model3D | None = None
    provenance: dict[str, Provenance] = {}

    @field_validator("id")
    @classmethod
    def check_id_format(cls, v: str) -> str:
        if not _LCSC_ID_RE.match(v):
            raise ValueError(
                f"id '{v}' must follow the pattern 'lcsc:C<number>' (e.g. lcsc:C77964)"
            )
        return v
