"""Fixed catalog of validation error/warning codes (stage 2).

These codes are a stable contract: the LLM operating fairypcbot uses them to decide how to
fix a YAML file. Do not rename an existing code without necessity — that breaks downstream
automation that may have learned to react to it.
"""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    E_YAML_SYNTAX = "E_YAML_SYNTAX"
    E_SCHEMA_INVALID = "E_SCHEMA_INVALID"
    E_SCHEMA_MISSING_FIELD = "E_SCHEMA_MISSING_FIELD"
    E_SCHEMA_INVALID_VALUE = "E_SCHEMA_INVALID_VALUE"
    E_UNKNOWN_PART_REF = "E_UNKNOWN_PART_REF"
    E_UNKNOWN_NET_REF = "E_UNKNOWN_NET_REF"
    E_UNKNOWN_PIN = "E_UNKNOWN_PIN"
    E_IMPORT_CYCLE = "E_IMPORT_CYCLE"
    E_IMPORT_NOT_FOUND = "E_IMPORT_NOT_FOUND"
    E_DUPLICATE_DESIGNATOR = "E_DUPLICATE_DESIGNATOR"
    E_INTENT_UNKNOWN_TYPE = "E_INTENT_UNKNOWN_TYPE"
    E_INTENT_BAD_PARAMS = "E_INTENT_BAD_PARAMS"
    E_CLASS_EXTENDS_CYCLE = "E_CLASS_EXTENDS_CYCLE"
    E_CLASS_NOT_FOUND = "E_CLASS_NOT_FOUND"

    W_PART_NOT_IN_LIBRARY = "W_PART_NOT_IN_LIBRARY"
    W_MODEL_NOT_IMPLEMENTED = "W_MODEL_NOT_IMPLEMENTED"

    # Electrical linter (stage 3 — elaborate, spec section 4)
    E_POWER_TREE_UNREACHABLE = "E_POWER_TREE_UNREACHABLE"
    W_CURRENT_OVER_TRACE_CAPACITY = "W_CURRENT_OVER_TRACE_CAPACITY"
    W_LOGIC_LEVEL_MISMATCH = "W_LOGIC_LEVEL_MISMATCH"
    W_FLOATING_REQUIRED_PIN = "W_FLOATING_REQUIRED_PIN"
    W_FLOATING_INPUT_PIN = "W_FLOATING_INPUT_PIN"
    W_FLOATING_DECLARED_PIN = "W_FLOATING_DECLARED_PIN"
    W_MISSING_DECOUPLING = "W_MISSING_DECOUPLING"
    W_PART_NOT_IN_ANY_NET = "W_PART_NOT_IN_ANY_NET"

    # Datasheets (self-sufficient library — M7)
    E_DATASHEET_NOT_FOUND = "E_DATASHEET_NOT_FOUND"
    W_DATASHEET_INCOMPLETE = "W_DATASHEET_INCOMPLETE"
    W_DATASHEET_VERSION_UNKNOWN = "W_DATASHEET_VERSION_UNKNOWN"
    W_PACKAGE_REF_NOT_FOUND = "W_PACKAGE_REF_NOT_FOUND"
